import { integer, pgTable, serial, text, timestamp, varchar, boolean } from "drizzle-orm/pg-core";
import { users } from "./users.schema";

export const UserInfomation = pgTable("user_infomation", {
    id: serial("id").primaryKey(),
    userId: integer("user_id").references(()=>users.id).notNull(),
    age: integer("age"),
    currentPositionDate: varchar("current_position_date", {length:255}).notNull(),
    requested_class: integer("requested_class"),
    homeProvince: varchar("home_province", {length:255}).notNull(),
    relationshipStatus: varchar("relationship_status", {length:255}).notNull(),
    house_number: varchar("house_number", {length:255}).notNull(),
    village_number: varchar("village_number", {length:255}).notNull(),
    alley: varchar("alley", {length:255}),
    soi: varchar("soi", {length:255}),
    province: varchar("province", {length:255}).notNull(),
    district:varchar("district", {length:255}).notNull(),
    subdistrict: varchar("subdistrict", {length:255}).notNull(),
    postal_code:varchar("postal_code", {length:255}).notNull(),
    phone_number: varchar("phone_number", {length:255}).notNull(),
    address_type: varchar("address_type", {length:255}).notNull(),
    spouse_name: varchar("spouse_name", {length:255}),
    spouse_office: varchar("spouse_office", {length:255}),
    spouse_house_number: varchar("spouse_house_number", {length:255}).notNull(),
    spouse_village_number: varchar("spouse_village_number", {length:255}).notNull(),
    spouse_alley: varchar("spouse_alley", {length:255}),
    spouse_soi: varchar("spouse_soi", {length:255}),
    spouse_province: varchar("spouse_province", {length:255}).notNull(),
    spouse_district:varchar("spouse_district", {length:255}).notNull(),
    spouse_subdistrict: varchar("spouse_subdistrict", {length:255}).notNull(),
    spouse_postal_code:varchar("spouse_postal_code", {length:255}).notNull(),
    spouse_phone_number: varchar("spouse_phone_number", {length:255}).notNull(),
    work_history: varchar("work_history", {length:255}).notNull(),
    work_history_date: varchar("work_history_date", {length:255}).notNull(),
    work_history_two: varchar("work_history_two", {length:255}),
    work_history_date_two: varchar("work_history_date_two", {length:255}),
    work_history_three: varchar("work_history_three", {length:255}),
    work_history_date_three: varchar("work_history_date_three", {length:255}),
});